#!/bin/bash

if [ ! -e sign.c ] ; then
	echo "File sign.c not found"
	exit
fi      

if [ ! -e  squash.awk ] ; then
   echo "File squash.awk not found"
	exit
fi

if [ ! -e  squash ] ; then
   echo "File squash not found"
	exit
fi

if [ ! -e  /usr/share/dict/words ] ; then
   echo "File dictionary not found"
   exit
fi


gcc -o sign ./sign.c
if [ ! -e "sign" ] ; then
echo "problem"
exit
fi

./sign < /usr/share/dict/words | sort | ./squash > out

./anagramCount < out | sort -n | tail

